#!/usr/bin/env bash

DIR="$(dirname $(greadlink -f ${BASH_SOURCE[0]} || readlink -f ${BASH_SOURCE[0]}))"

# only creates a virtualenv folder if it doesn't exist before
if [[ ! -d "$DIR/venv" ]]; then
    virtualenv $DIR/venv > /dev/null
fi


source $DIR/venv/bin/activate
pip install -r $DIR/requirements.txt > /dev/null
while true; do python $DIR/run_f1_app.py | nc -l 2727; done
