"""created_at and update_at deleted

Revision ID: 18408ea142f8
Revises: 6c578fb6ad2b
Create Date: 2020-09-16 13:06:27.204961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18408ea142f8'
down_revision = '6c578fb6ad2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'updated_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('updated_at', sa.DATE(), nullable=True))
    op.add_column('user', sa.Column('created_at', sa.DATE(), nullable=True))
    # ### end Alembic commands ###
