"""added logged in

Revision ID: 55b09009d413
Revises: b230ad3c9217
Create Date: 2020-08-26 13:52:41.210668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b09009d413'
down_revision = 'b230ad3c9217'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_logged_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_logged_in')
    # ### end Alembic commands ###
