"""created and updated added for user

Revision ID: 6c578fb6ad2b
Revises: 9f19a1d81418
Create Date: 2020-09-07 14:48:01.585925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c578fb6ad2b'
down_revision = '9f19a1d81418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.Date(), nullable=True))
    op.drop_column('user', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
